### ISSUE TITLE
Publish OML Luxor VSIX File to VSCode Extension Marketplace

### ISSUE THREAD

**Issue by pogi7** [opencaesar/oml-vscode#37]
## User Story
As a **OML Luxor user**, I would like **to publish the OML Luxor VSIX File to the VSCode Extension Marketplace** so that **updating the extension from the user end is much easier**.

## Detailed Description
VSCode extensions can be published on the VSCode Extension Marketplace.  This allows for extensions to be easily managed by Microsoft and allows for updates to be done much easier through the VSCode Extensions service in VSCode.

An example of a VSCode extension published to the VSCode Extension Marketplace is 
https://marketplace.visualstudio.com/items?itemName=pteam-ptolemy.oml-alexandria

## Acceptance Criteria
- [ ] Given **OML Luxor VSIX File**, then **publish file to VSCode Extension Marketplace**
- [ ] Given **OML Luxor VSIX File on Marketplace**, then **downloads/upgrades can be performed from the VSCode Extensions service in VSCode IDE.**

## Sub-task List
- [ ] Publish OML Luxor VSIX File to VSCode Extension Marketplace
- [ ] Download OML Luxor VSIX file from VSCode Extension Marketplace within VSCode IDE
